"""Initial migration

Revision ID: e3e51ef1cbca
Revises: None
Create Date: 2025-09-01 13:58:47.626394
"""

# revision identifiers, used by Alembic.
revision = 'e3e51ef1cbca'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

